import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/homePage/NavBar";
import NavForMobile from "@/Components/homePage/NavForMobile";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "JobNow",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <NavBar />
            <NavForMobile />
            {children}
         </body>
      </html>
   );
}
